#!/usr/bin/env python3
"""Generate the override tables of the 4 GW nuclear scenario family.

The cabinet's two scenarios, presented on an equal footing (A. Dubois,
7 Oct 2026):

* Scenario 1, "3 GW": Tihange 3 prolonged + 2 GW of new nuclear — the central
  (`scen_central`, `scen_biomethane_industrie`, `scen_noccsccgt`).
* Scenario 2, "4 GW": the same plus **Tihange 1** brought back. ICEDD and the
  cabinet (6-7 Oct): back in 2035, no capacity in 2030, prolongation cost of
  Tihange 3 (10 years, renewable). On the 10-year grid that means from 2040.

Scenario 2 is Scenario 1 plus Tihange 1 and nothing else, so S2 − S1 isolates
the restart. Every Walloon `nuclear-all` min/max row from 2035 on is the
central's plus ``T1_MW``, and the BE parent rows move by the same amount
(`add_CCL_constraints` subtracts the regional rows from BE, so BE must stay
BEWAL + BEVLG). Flanders is untouched. 2025/2030 keep no row: Tihange 3 alone
stands then. The new build is the central's (3 000 − 1 030 MW in 2050).

| BEWAL, MW_e (min/max) | 2035 | 2040 | 2045 | 2050 |
|---|---|---|---|---|
| central (3 GW) | 1000/1030 | 1000/1030 | 1750/1750 | 3000/3000 |
| + Tihange 1 (4 GW) | 1962/1992 | 1962/1992 | 2712/2712 | 3962/3962 |

The restart itself is `electricity.nuclear_restart` (Tihange 1, from 2035),
switched on in the three scenario blocks. Without it the 2040 floor would be
met by new build at 9 500 EUR/kW.

Three files, one per scenario of the family:

* ``scen_nuc4gw``                      the nuclear rows;
* ``scen_nuc4gw_biomethane_industrie`` the same rows (the biomethane
  sensitivity has no PyPSA-side delta, only its own TIMES export);
* ``scen_nuc4gw_noccsccgt``            the nuclear rows + every row of
  ``config/scenarios/scen_noccsccgt.csv`` (power-plant capture at 0 MW).

Usage:
    python scripts/walloon_scripts/make_nuc4gw_scenarios.py            # write
    python scripts/walloon_scripts/make_nuc4gw_scenarios.py --dry-run
    python scripts/walloon_scripts/make_nuc4gw_scenarios.py --t1-mw 1000

Then materialise the input files:
    python scripts/build_common_parameters.py --write --all-scenarios

`test/test_nuc4gw_scenarios.py` fails if a file drifts from this generator.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
MASTER = ROOT / "config" / "input_parameters_for_models.csv"
OUT_DIR = ROOT / "config" / "scenarios"
NOCCSCCGT = OUT_DIR / "scen_noccsccgt.csv"

# Tihange 1 net capacity, data/walloon/wal_2021_existing_capacities_2.csv.
T1_MW = 962

TARGETS = (
    "agg:BEWAL:nuclear-all:min",
    "agg:BEWAL:nuclear-all:max",
    "agg:BE:nuclear-all:min",
    "agg:BE:nuclear-all:max",
)
YEARS = (2035.0, 2040.0, 2045.0, 2050.0)

SOURCE = (
    "Scénario 2 « 4 GW nucléaire » (cabinet, A. Dubois 7 Oct 2026): Tihange 1 "
    "remis en service en 2035 au coût de prolongation de Tihange 3 (ICEDD 6-7 Oct)"
)

FAMILY = ("scen_nuc4gw", "scen_nuc4gw_biomethane_industrie", "scen_nuc4gw_noccsccgt")


def nuclear_rows(master: pd.DataFrame, t1_mw: float = T1_MW) -> pd.DataFrame:
    """The central's BEWAL / BE nuclear rows from 2035, each raised by ``t1_mw``."""
    rows = []
    for target in TARGETS:
        for year in YEARS:
            sel = master[(master["pypsa_wal_target"] == target) & (master["year"] == year)]
            if len(sel) != 1:
                sys.exit(f"master CSV: expected one row {target} @ {year:.0f}, found {len(sel)}")
            row = sel.iloc[0].copy()
            old = float(row["value"])
            row["value"] = old + float(t1_mw)
            row["source"] = SOURCE
            row["note_complementaire"] = (
                f"{old:.0f} -> {old + t1_mw:.0f} MW: the central (3 GW) plus Tihange 1, "
                f"{t1_mw:.0f} MW_e, restarted from 2035 by electricity.nuclear_restart "
                "at the nuclear retrofit cost (Tihange 3, 10 years, renewable). New build "
                "unchanged, so scen_nuc4gw - scen_central is the restart alone. "
                "Generated by scripts/walloon_scripts/make_nuc4gw_scenarios.py."
            )
            rows.append(row)
    return pd.DataFrame(rows)[master.columns.tolist()]


def build_family(master: pd.DataFrame, noccsccgt: pd.DataFrame, t1_mw: float = T1_MW) -> dict:
    nuc = nuclear_rows(master, t1_mw)
    clash = set(zip(nuc["pypsa_wal_target"], nuc["year"])) & set(
        zip(noccsccgt["pypsa_wal_target"], noccsccgt["year"])
    )
    if clash:
        sys.exit(f"scen_noccsccgt.csv overrides nuclear rows too: {sorted(clash)}")
    combo = pd.concat([nuc, noccsccgt[master.columns.tolist()]], ignore_index=True)
    return {
        "scen_nuc4gw": nuc,
        "scen_nuc4gw_biomethane_industrie": nuc.copy(),
        "scen_nuc4gw_noccsccgt": combo,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--t1-mw", type=float, default=T1_MW,
                    help=f"Tihange 1 capacity added to every row, MW_e (default {T1_MW})")
    ap.add_argument("--dry-run", action="store_true", help="print, write nothing")
    args = ap.parse_args()

    master = pd.read_csv(MASTER)
    family = build_family(master, pd.read_csv(NOCCSCCGT), args.t1_mw)
    for name, frame in family.items():
        path = OUT_DIR / f"{name}.csv"
        print(f"{'would write' if args.dry_run else 'wrote'} "
              f"{path.relative_to(ROOT)}  ({len(frame)} override rows)")
        if not args.dry_run:
            frame.to_csv(path, index=False, lineterminator="\n")
    print("\nNext:\n  python scripts/build_common_parameters.py --write --all-scenarios")
    return 0


if __name__ == "__main__":
    sys.exit(main())
