# SPDX-FileCopyrightText: Contributors to PyPSA-Wal
# SPDX-License-Identifier: MIT
"""
LaTeX macros and table fragments for docs/pv_potential_wallonia/.

Every number the report quotes is a macro written here from the workflow's
outputs, so the text cannot drift from the calculation.  Macro names are
CamelCase versions of the workflow keys: ``\\GSarRefMW`` is the reference
capacity of the ``sar`` gisement, ``\\SAgriQuotaPct`` the change a case makes,
``\\LNaturaKm`` the area of a burnt layer.
"""

import json
import re
from pathlib import Path

import pandas as pd

GROUP_LABEL = {"policy": "policy", "judgement": "judgement", "technical": "technical"}


def camel(key):
    key = key.replace("06", "ZeroSix")
    parts = re.split(r"[_\-\s]+", key)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    # LaTeX command names take letters only
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five",
              "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    return "".join(digits.get(c, c) for c in out)


def num(x, d=0):
    """1234567.8 -> 1\\,234\\,568 (thin-space thousands, decimal point)."""
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "--"
    s = f"{x:,.{d}f}"
    return s.replace(",", "\\,")


def gw(mw, d=1):
    return num(mw / 1000.0, d)


class Macros:
    def __init__(self):
        self.lines = []
        self.names = set()

    def add(self, name, value):
        if name in self.names:
            raise ValueError(f"duplicate macro {name}")
        self.names.add(name)
        self.lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    def text(self):
        return "% Generated by workflow_pv_wal/scripts/make_report_inputs.py -- do not edit.\n" + \
            "\n".join(self.lines) + "\n"


def tex_escape(s):
    return (str(s).replace("\\", "\\textbackslash{}").replace("&", "\\&").replace("%", "\\%")
            .replace("_", "\\_").replace("#", "\\#").replace("$", "\\$")
            .replace("§", "\\S{}").replace("°", "\\textdegree{}").replace("—", "---")
            .replace("–", "--").replace("²", "\\textsuperscript{2}").replace("…", "\\ldots{}"))


if __name__ == "__main__":
    if "snakemake" not in globals():
        raise SystemExit("run through snakemake")

    cfg = snakemake.params.config
    head = json.loads(Path(snakemake.input.headline).read_text())
    detail = json.loads(Path(snakemake.input.detail).read_text())
    sens = pd.read_csv(snakemake.input.sensitivity)
    fleet = json.loads(Path(snakemake.input.fleet).read_text())
    avoid = pd.read_csv(snakemake.input.avoidance)
    parks = pd.read_csv(snakemake.input.parks)
    energy = json.loads(Path(snakemake.input.energy).read_text())
    grid = json.loads(Path(snakemake.input.grid).read_text())
    M = Macros()
    B = cfg["benchmarks"]

    # ---- region, funnel -------------------------------------------------------------
    region_ha = head["region_ha"]
    M.add("RegionKm", num(region_ha / 100))
    M.add("GridRes", num(grid["res"]))
    prev = region_ha
    for f in head["funnel"]:
        k = camel(f["family"])
        M.add(f"Left{k}Km", num(f["left_ha"] / 100))
        M.add(f"Left{k}Pct", num(100 * f["left_ha"] / region_ha, 1))
        M.add(f"Drop{k}Km", num((prev - f["left_ha"]) / 100))
        prev = f["left_ha"]
    park = next(f for f in head["funnel"] if f["family"] == "park_rule")
    M.add("FloatHa", num(park["floating_ha"]))

    # ---- gisements ---------------------------------------------------------------------
    g = head["gisements"]
    agri = [k for k, v in g.items() if v["system"].startswith("agrivoltaic")]
    for k, v in g.items():
        c = camel(k)
        M.add(f"G{c}EligHa", num(v["eligible_ha"]))
        M.add(f"G{c}TechHa", num(v["after_park_rule_ha"]))
        M.add(f"G{c}OpenHa", num(v["open_ha"]))
        M.add(f"G{c}TechMW", num(v["technical_mwc"]))
        M.add(f"G{c}TechGW", gw(v["technical_mwc"]))
        M.add(f"G{c}RefMW", num(v["policy_mwc"]))
    ref = head["reference"]
    M.add("RefMW", num(ref["policy_mwc"]))
    M.add("RefGW", gw(ref["policy_mwc"]))
    M.add("RefHa", num(ref["open_ha"]))
    M.add("TechMW", num(ref["technical_mwc"]))
    M.add("TechGW", gw(ref["technical_mwc"], 0))
    tech_nonagri = sum(v["technical_mwc"] for k, v in g.items() if k not in agri)
    tech_agri = sum(v["technical_mwc"] for k in agri for v in [g[k]])
    M.add("TechNonAgriGW", gw(tech_nonagri))
    M.add("TechAgriGW", gw(tech_agri, 0))
    agri_ha = sum(g[k]["after_park_rule_ha"] for k in agri)
    M.add("TechAgriHa", num(agri_ha))
    M.add("TechAgriShareSau", num(100 * agri_ha / B["sau_ha"], 0))
    deg = ["sar", "cet", "terril", "extraction", "infra_edge", "water_industrial"]
    M.add("RefCapHa", num(ref["agri_cap_ha"] or 0))
    M.add("RefDegradedGW", gw(sum(g[k]["policy_mwc"] for k in deg)))
    M.add("RefZaeGW", gw(g["zae"]["policy_mwc"] + g["zspec"]["policy_mwc"]))
    M.add("RefZaeShare", num(100 * ref["shares"]["zae"]))
    # the park rule re-applied: what filtering once would have given
    M.add("ParkMinHa", num(cfg["park"]["min_area_ha"], 0))
    M.add("ParkMinWidth", num(cfg["park"]["min_width_m"]))

    # ---- densities, policy ------------------------------------------------------------
    for k, v in cfg["densities_mwc_ha"].items():
        c = camel(k)
        M.add(f"Dens{c}", num(v["ref"], 2))
        M.add(f"Dens{c}Low", num(v["low"], 2))
        M.add(f"Dens{c}High", num(v["high"], 2))
    M.add("FloatCover", num(100 * cfg["floating"]["coverage"]["ref"]))
    M.add("SlopeMax", num(cfg["terrain"]["max_slope_pct"]))
    M.add("NorthMax", num(cfg["terrain"]["north_max_slope_pct"]))
    M.add("BuiltPct", num(cfg["walous"]["thresholds_pct"]["built"]))
    M.add("SealedPct", num(cfg["walous"]["thresholds_pct"]["sealed"]))
    M.add("TreesPct", num(cfg["walous"]["thresholds_pct"]["trees"]))
    M.add("SauHa", num(B["sau_ha"]))
    M.add("SauKha", num(B["sau_ha"] / 1000))

    # ---- soil evidence -------------------------------------------------------------
    ev = json.loads(Path(snakemake.input.evidence).read_text())
    M.add("EvShare", num(100 * ev["share"], 1))
    for k, v in ev["steps_ha"].items():
        M.add(f"Ev{camel(k.replace('_ha', ''))}Ha", num(v))
    fs = ev["farmed_share_by_awac_class"]
    for c in range(1, 6):
        M.add(f"EvFarmedClass{['One', 'Two', 'Three', 'Four', 'Five'][c - 1]}", num(100 * fs.get(str(c), fs.get(c, 0)), 0))
    M.add("EvUnfarmedPoor", num(100 * ev["unfarmed_share_poor"], 1))
    M.add("EvUnfarmedOther", num(100 * ev["unfarmed_share_other"], 1))
    M.add("EvPoorRegionHa", num(ev["poor_soils_region_ha"]))
    M.add("EvPoorFarmedHa", num(ev["poor_soils_farmed_ha"]))
    M.add("EvPoorFarmedPct", num(100 * ev["poor_soils_farmed_ha"] / ev["poor_soils_region_ha"], 0))
    stony = sum(v for k, v in ev["poor_soils_by_cnsw_ha"].items() if str(k).startswith("7"))
    M.add("EvPoorStonyPct", num(100 * stony / ev["poor_soils_region_ha"], 0))
    M.add("EvCurtilage", num(ev["curtilage_m"]))

    # ---- sensitivity ------------------------------------------------------------------
    for _, r in sens.iterrows():
        if r["case"] == "reference":
            continue
        c = camel(r["case"])
        M.add(f"S{c}MW", num(r["policy_mwc"]))
        M.add(f"S{c}GW", gw(r["policy_mwc"]))
        M.add(f"S{c}DeltaGW", ("+" if r["delta_mwc"] >= 0 else "$-$") + gw(abs(r["delta_mwc"])))
        M.add(f"S{c}Pct", ("+" if r["delta_pct"] >= 0 else "$-$") + num(abs(r["delta_pct"]), 0))
        d = detail[r["case"]]["total"]
        if d.get("agri_cap_ha") is not None:
            M.add(f"S{c}CapHa", num(d["agri_cap_ha"]))

    # ---- fleet ----------------------------------------------------------------------------
    M.add("FleetN", num(fleet["parks"]))
    M.add("FleetHa", num(fleet["area_ha"]))
    M.add("FleetEligPct", num(100 * fleet["share_of_fleet_area_eligible"]))
    M.add("FleetEligRulesPct", num(100 * fleet["share_of_fleet_area_eligible_without_landcover_built"]))
    M.add("FleetTagged", num(fleet["tagged_parks_ge_1ha"]))
    M.add("FleetDensMedian", num(fleet["density_mwc_ha_median"] or 0, 2))
    M.add("FleetDensWeighted", num(fleet["density_mwc_ha_area_weighted"] or 0, 2))
    for _, r in avoid[avoid["kind"] == "family"].iterrows():
        c = camel(r["family"])
        M.add(f"FleetAvoid{c}", num(r["avoidance"], 2) if pd.notna(r["avoidance"]) else "--")
        M.add(f"FleetShare{c}", num(100 * r["share_fleet"], 0))
        M.add(f"RegionShare{c}", num(100 * r["share_region"], 0))
    gis_n = fleet["gisement_of_parks_n"]
    gis_ha = fleet["gisement_of_parks_ha"]
    for k in [x["key"] for x in cfg["gisements"]] + ["outside"]:
        c = camel(k)
        M.add(f"FleetOn{c}N", num(gis_n.get(k, 0)))
        M.add(f"FleetOn{c}Ha", num(gis_ha.get(k, 0)))

    # ---- energy -------------------------------------------------------------------------------
    for k, v in energy.items():
        M.add(f"Flh{camel(k)}", num(v["flh_h"]))
    ref_twh = sum(v["policy_mwc"] * energy[v["system"]]["flh_h"] for v in g.values()) / 1e6
    M.add("RefTWh", num(ref_twh, 1))

    # ---- layers ---------------------------------------------------------------------------------
    for p in snakemake.input.layer_stats:
        s = json.loads(Path(p).read_text())
        M.add(f"L{camel(s['layer'])}Km", num(s["area_km2"]))

    # ---- benchmarks -------------------------------------------------------------------------------
    M.add("ModelCapMW", num(B["model_p_nom_max_mw"]))
    M.add("ModelCapGW", gw(B["model_p_nom_max_mw"], 0))
    M.add("ModelRoofGW", gw(B["model_rooftop_p_nom_max_mw"], 0))
    M.add("PypsaEurGW", gw(B["pypsa_eur_land_mw"], 0))
    M.add("InstalledGW", gw(B["installed_total_2025_mwc"]))
    M.add("PaceGWh", num(B["pace_2030_gwh"]))
    M.add("PaceGW", num(B["pace_2030_gwc"], 0))
    M.add("ApereGW", num(B["apere_brownfields_gwc"], 1))
    M.add("LbRemainingMW", num(B["livre_blanc_remaining_mwc"]))
    M.add("LbRemainingHa", num(B["livre_blanc_remaining_ha"]))
    for i, v in enumerate(B["glaes_scenarios_ha"]):
        M.add(f"Glaes{['One', 'Two', 'Three'][i]}Ha", num(v))
    M.add("RefOverModel", num(ref["policy_mwc"] / B["model_p_nom_max_mw"] * 100, 0))
    agri_ref = sum(g[k]["policy_mwc"] for k in agri)
    M.add("RefAgriGW", gw(agri_ref))
    M.add("RefAgriHa", num(sum(g[k]["open_ha"] for k in agri)))
    M.add("RefPoorMW", num(g["agri_zone_poor"]["policy_mwc"]))
    M.add("RefNonAgriGW", gw(ref["policy_mwc"] - agri_ref))
    M.add("ModelOverRef", num(B["model_p_nom_max_mw"] / ref["policy_mwc"], 1))

    out = Path(snakemake.output.macros)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(M.text())

    # ---- tables -------------------------------------------------------------------------------------
    labels = snakemake.params.labels
    rows = []
    for k, v in g.items():
        rows.append(f"{tex_escape(labels.get(k, k))} & {tex_escape(v['system'].replace('_', ' '))} & "
                    f"{num(v['eligible_ha'])} & {num(v['after_park_rule_ha'])} & "
                    f"{num(v['mwc_per_ha'], 2)} & {num(v['technical_mwc'])} & "
                    f"{num(ref['shares'].get(k, 0) * 100, 1 if 0 < ref['shares'].get(k, 0) < 0.1 else 0)} & "
                    f"{num(v['policy_mwc'])} \\\\")
    rows.append("\\midrule")
    rows.append(f"Total & & {num(ref['eligible_ha'])} & {num(ref['after_park_rule_ha'])} & & "
                f"{num(ref['technical_mwc'])} & & \\textbf{{{num(ref['policy_mwc'])}}} \\\\")
    Path(snakemake.output.gisements).write_text("\n".join(rows) + "\n")

    rows = []
    for grp in ["policy", "judgement", "technical"]:
        sub = sens[sens["group"] == grp]
        if sub.empty:
            continue
        rows.append(f"\\multicolumn{{4}}{{l}}{{\\emph{{{grp}}}}} \\\\")
        for _, r in sub.iterrows():
            rows.append(f"\\quad {tex_escape(r['label'])} & {num(r['policy_mwc'])} & "
                        f"{('+' if r['delta_mwc'] >= 0 else '$-$') + num(abs(r['delta_mwc']))} & "
                        f"{('+' if r['delta_pct'] >= 0 else '$-$') + num(abs(r['delta_pct']), 0)} \\\\")
    Path(snakemake.output.sensitivity).write_text("\n".join(rows) + "\n")

    rows = []
    fam = avoid[avoid["kind"].isin(["family", "terrain"])]
    for _, r in fam.iterrows():
        rows.append(f"{tex_escape(r['rule'].replace('family:', ''))} & {num(100 * r['share_region'], 1)} & "
                    f"{num(100 * r['share_fleet'], 1)} & "
                    f"{num(r['avoidance'], 2) if pd.notna(r['avoidance']) else '--'} & "
                    f"{int(r['parks_mostly_inside'])} \\\\")
    Path(snakemake.output.fleet).write_text("\n".join(rows) + "\n")

    rows = []
    top = parks.head(15)
    for _, r in top.iterrows():
        rows.append(f"{tex_escape(r['name'] if isinstance(r['name'], str) else '(unnamed)')} & "
                    f"{num(r['area_ha'], 1)} & "
                    f"{num(r['mw_tag'], 1) if pd.notna(r['mw_tag']) else '--'} & "
                    f"{num(r['mwc_per_ha'], 2) if pd.notna(r['mwc_per_ha']) else '--'} & "
                    f"{tex_escape(labels.get(r['gisement'], r['gisement']))} & "
                    f"{num(100 * r['share_eligible'], 0) if pd.notna(r['share_eligible']) else '--'} \\\\")
    Path(snakemake.output.parks).write_text("\n".join(rows) + "\n")

    rows = []
    for p in snakemake.input.source_meta:
        m = json.loads(Path(p).read_text())
        rows.append(f"{tex_escape(m.get('title') or '')} & \\texttt{{{tex_escape(m['service'])}/{m['layer']}}} & "
                    f"{num(m['features_written'])} & {m['retrieved'][:10]} \\\\")
    Path(snakemake.output.sources).write_text("\n".join(rows) + "\n")
