scen_base_2013:

  atlite:
    default_cutout: "europe-2013-sarah3-era5"
    nprocesses: 4

  snapshots:
    start: "2013-01-01"
    end: "2014-01-01"
    inclusive: left

  sector:
    times_file: data/walloon/scen_base_251130_0412.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_corrige.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_corrige.csv
  solving:
    agg_p_nom_limits:
      file: data/walloon/agg_p_nom_minmax_base.csv

scen_base_2010:

  atlite:
    default_cutout: "europe-2010-sarah3-era5"
    nprocesses: 4

  snapshots:
    start: "2010-01-01"
    end: "2011-01-01"
    inclusive: left

  sector:
    times_file: data/walloon/scen_base_251130_0412.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_corrige.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_corrige.csv
  solving:
    agg_p_nom_limits:
      file: data/walloon/agg_p_nom_minmax_base.csv

scen_corrige:
  sector:
    times_file: data/walloon/scen_corrige_251130_0312.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_corrige.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_corrige.csv
  solving:
    agg_p_nom_limits:
      file: data/walloon/agg_p_nom_minmax_corrige.csv


scen_nuc13500:
  sector:
    times_file: data/walloon/scen_corrige_nuc13500_251205_0512.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_corrige.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_nuc13500.csv
  solving:
    agg_p_nom_limits:
      file: data/agg_p_nom_minmax.csv

scen_nuc11500:
  sector:
    times_file: data/walloon/scen_corrige_nuc11500_251205_0512.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_corrige.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_nuc11500.csv
  solving:
    agg_p_nom_limits:
      file: data/agg_p_nom_minmax.csv

scen_imppel:
  sector:
    times_file: data/walloon/scen_corrige_imppel_251130_0412.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_imppel.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_corrige.csv
  solving:
    agg_p_nom_limits:
      file: data/walloon/agg_p_nom_minmax_corrige.csv

scen_data:
  sector:
    times_file: data/walloon/scen_corrige_data_251130_0412.vd
  electricity:
    walloon_potentials: data/walloon/custom_potentials_corrige.csv
  costs:
    custom_cost_fn: data/walloon/custom_costs_corrige.csv
  solving:
    agg_p_nom_limits:
      file: data/walloon/agg_p_nom_minmax_corrige.csv
